# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='电影分类')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': '电影类别',
                'verbose_name_plural': '电影类别',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=30, verbose_name='电影名字')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/picture', verbose_name='影片图片')),
                ('show_data', models.DateField(verbose_name='上映时间')),
                ('director', models.CharField(max_length=30, verbose_name='导演')),
                ('screenwriter', models.CharField(max_length=100, verbose_name='编剧')),
                ('type', models.CharField(max_length=30, verbose_name='电影类型')),
                ('long_time', models.CharField(max_length=30, verbose_name='电影时长')),
                ('stars', models.CharField(max_length=200, verbose_name='主演')),
                ('synopsis', models.TextField(verbose_name='剧情介绍')),
                ('movie_score', models.FloatField(verbose_name='评分')),
                ('release_date', models.DateField(auto_now=True, verbose_name='发表时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Category')),
            ],
            options={
                'db_table': 'films',
                'verbose_name': '影片',
                'ordering': ['-movie_score'],
                'verbose_name_plural': '影片',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readed', models.IntegerField(default=0, verbose_name='已阅读')),
                ('like', models.IntegerField(default=0, verbose_name='赞')),
                ('reply_number', models.IntegerField(default=0, verbose_name='评论次数')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Films')),
            ],
            options={
                'db_table': 'info',
                'verbose_name': '影片信息',
                'verbose_name_plural': '影片信息',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('reply_date', models.DateField(auto_now=True, verbose_name='回复时间')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Films')),
            ],
            options={
                'db_table': 'reply',
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('upwd', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='films',
            name='user',
            field=models.ManyToManyField(to='index.User'),
        ),
    ]
