# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='readed',
            new_name='read_number',
        ),
        migrations.RemoveField(
            model_name='info',
            name='like',
        ),
        migrations.AddField(
            model_name='info',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
