# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181204_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='show_data',
            new_name='show_date',
        ),
    ]
